on:
  pull_request:
    types: [opened, synchronize]
jobs:
  code_review:
    runs-on: ubuntu-latest
    name: openai code review
    steps:
      - name: openai
        uses: crnvl96/openai-golang-github-integration@1.0.14
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
